alias b='bundle'
alias be='bundle exec'
alias e='vim'
alias et='ember test --server'
alias g='git'
alias ga='git aa'
alias gb='git branch'
alias gc='git commit -v'
alias gca='git commit -a -v'
alias gco='git checkout'
alias gd='git diff'
alias gdc='git diff --cached'
alias gds='git diff --stat'
alias gl='git pull --prune'
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias gp='git push'
alias gpf='git push --force-with-lease'
alias grc='git rebase --continue'
alias grep='grep --ignore-case --color'
alias gri='git rebase -i origin/master'
alias gs='git status -sb'
alias ll='ls -al'
alias ln='ln -v'
alias mkdir='mkdir -p'
alias nombom='rm -rf {bower_components,dist,node_modules,tmp}'
alias rk='rake'
alias s='rspec'

set fish_greeting
set -x PATH $HOME/.bin $PATH
